Add homework2
sansnome/MargaritaMalygina_LevelUP pull request #6
Opened 2022-12-01 13:55 UTC by sansnome

Добрый день!
Добавила ДЗ №2 (на ветке homework2 директория homework2).

2022-12-01 14:31 UTC, khda91 requested changes
Пожалуйста, исправь комментарии

2022-12-01 14:31 UTC, khda91 commented on homework2/pom.xml
> +
1. Не вижу зависимости на **junit** или **testng**
2. Не вижу профайлов maven для запуска тестов по suite
3. Отсутсвует checkstyle плагин

2022-12-01 14:31 UTC, khda91 commented on homework2/src/main/java/ru.levelup.at/homework2/App.java
> +package ru.levelup.at.homework2;public class App {
Зачем нужен этот класс?

2022-12-01 14:31 UTC, khda91 commented on homework2/src/main/java/ru.levelup.at/homework2/BusTicket.java
> +package ru.levelup.at.homework2;public class BusTicket {
Зачем нужен этот класс?

2022-12-01 14:31 UTC, khda91 commented on homework2/src/main/java/ru.levelup.at/homework2/LuckyTicket.java
> +package ru.levelup.at.homework2;public class LuckyTicket {
Зачем нужен этот класс?

2022-12-01 14:31 UTC, khda91 commented on homework2/src/test/java/ru/levelup/at/homework2/AllTestSuite.java
> +package ru.levelup.at.homework2;public class AllTestSuite {
Зачем нужен этот класс?

2022-12-01 14:31 UTC, khda91 commented on homework2/src/test/java/ru/levelup/at/homework2/NegativeTestSuite.java
> +package ru.levelup.at.homework2;public class NegativeTestSuite {
Зачем нужен этот класс?

2022-12-01 14:31 UTC, khda91 commented on homework2/src/test/java/ru/levelup/at/homework2/PositiveTestSuite.java
> +package ru.levelup.at.homework2;public class PositiveTestSuite {
Зачем нужен этот класс?

2022-12-01 14:31 UTC, khda91 commented on homework2/src/test/java/ru/levelup/at/homework2/LuckyTicketNegativeTest.java
> +        boolean actual = LuckyTicket.isLucky(input);
А где реализация класса `LuckyTicket`?

2022-12-01 14:31 UTC, khda91 commented on homework2/src/test/java/ru/levelup/at/homework2/LuckyTicketPositiveTest.java
> +    }
А почему данный тест считается позитивным?

2022-12-01 15:13 UTC, sansnome commented on homework2/pom.xml
> +
Обновлен pom.xml до актуальной версии с зависимостями, плагинами, профайлами.

2022-12-01 15:14 UTC, sansnome commented on homework2/src/main/java/ru.levelup.at/homework2/BusTicket.java
> +package ru.levelup.at.homework2;public class BusTicket {
Добавлен комментарий с описанием назначения класса

2022-12-01 15:14 UTC, sansnome commented on homework2/src/test/java/ru/levelup/at/homework2/LuckyTicketPositiveTest.java
> +    }
Обновлена версия файла до актуальной (данный тест отсутствует здесь, перенесен в LuckyTicketNegativeTest.java).

2022-12-01 15:15 UTC, sansnome commented on homework2/src/test/java/ru/levelup/at/homework2/LuckyTicketNegativeTest.java
> +        boolean actual = LuckyTicket.isLucky(input);
Добавлена реализация класса LuckyTicket

2022-12-01 15:15 UTC, sansnome commented on homework2/src/main/java/ru.levelup.at/homework2/LuckyTicket.java
> +package ru.levelup.at.homework2;public class LuckyTicket {
Добавлен комментарий с описанием назначения класса

2022-12-01 15:15 UTC, sansnome commented on homework2/src/test/java/ru/levelup/at/homework2/PositiveTestSuite.java
> +package ru.levelup.at.homework2;public class PositiveTestSuite {
Добавлен комментарий с описанием назначения класса

2022-12-01 15:15 UTC, sansnome commented on homework2/src/test/java/ru/levelup/at/homework2/AllTestSuite.java
> +package ru.levelup.at.homework2;public class AllTestSuite {
Добавлен комментарий с описанием назначения класса

2022-12-01 15:17 UTC, sansnome commented on homework2/src/test/java/ru/levelup/at/homework2/NegativeTestSuite.java
> +package ru.levelup.at.homework2;public class NegativeTestSuite {
Добавлен комментарий с описанием назначения класса

2022-12-06 06:07 UTC, khda91 approved these changes
Работа принята

2022-12-08 16:15 UTC, merged